name: Deploy

on:
  push:
    branches:
      - develop
      - main

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set staging environment variables
        if: ${{ github.ref == 'refs/heads/develop' }}
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME_STAGING }}
        run: echo "HEROKU_APP_NAME=$HEROKU_APP_NAME" >> $GITHUB_ENV

      - name: Set production environment variables
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME_PRODUCTION }}
        run: echo "HEROKU_APP_NAME=$HEROKU_APP_NAME" >> $GITHUB_ENV

      - name: Login to Heroku Container registry
        run: heroku container:login

      - name: Build and push
        run: heroku container:push -a $HEROKU_APP_NAME web

      - name: Release
        run: heroku container:release -a $HEROKU_APP_NAME web
